### ISSUE TITLE
Make dunst-Window disappear automatically

### ISSUE THREAD

**Issue by riotbib** [geistesk/et#1]
Hi there @geistesk, thanks a lot for `et`.

Could you make it so that the dunst-Window disappers automatically and doesn't need a click to disappear?

Cheers.

**Comment by oxzi** [comment]
Hello,
thank you for opening an issue and thanks a lot for the compliment.

*et* interacts directly with *libnotify*, which passes a notification to your notification daemon via D-Bus. The notification daemon, *dunst* in your case, presents you the notification's data based on its implementation and configuration.

The *Desktop Notifications Specification* lists three [Urgency Levels](https://developer.gnome.org/notification-spec/#urgency-levels): *low*, *normal* and *critical*. Each notification sent to a notification daemon needs an urgency level and may be processed differently based on its assigned urgency.

*et* is creating notifications of two different urgency types:

- The initial time shown after starting up and the requested time through `SIGUSR1` is shown with the *normal* urgency.
- However, after the timer runs out, a *critical* notification will be created. As specified in the *Desktop Notifications Specification*, "[c]ritical notifications should not automatically expire, as they are things that the user will most likely want to know about." Because of my main usage of this software, to inform me about the state of my food, I really do not want to miss such a notification.

As mentioned above, one should be able to configure the behavior of the used notification daemon. Your selected daemon, *dunst*, is easy to configure by editing its configuration file `~/.config/dunst/dunstrc`. The three `[urgency_$URGENCY_TYPE]` categories each have a `timeout` variable, which determines when your notification will expire. In addition to the urgency based configuration, rules for special pattern can be added, which will override the defaults. Therefore you should be able to dispatch *et*'s notification with an extra rule.

I hope this answer will help you.

**Comment by riotbib** [comment]
Hej @geistesk thanks a lot for your in-depth answer.

I decided to let it be as is, as your cooking example is quite persuasive.
