### ISSUE TITLE
Cannot compile with 'undefined reference'

### ISSUE THREAD

**Issue by egormanga** [geistesk/et#2]
<pre><font color="#8AE234"><b>egormanga@ACER-TOUCH</b></font>:<font color="#729FCF"><b>~/et</b></font>$ make
cc -Wall -Wextra -pedantic --std=c11 -Ofast `pkg-config --cflags glib-2.0 gdk-pixbuf-2.0 --libs libnotify` -c et.c
cc -Wall -Wextra -pedantic --std=c11 -Ofast `pkg-config --cflags glib-2.0 gdk-pixbuf-2.0 --libs libnotify` -o et et.o
et.o: In function `show_notification&apos;:
et.c:(.text+0xa5): undefined reference to `notify_notification_new&apos;
et.c:(.text+0xb2): undefined reference to `notify_notification_set_urgency&apos;
et.c:(.text+0xbc): undefined reference to `notify_notification_show&apos;
et.c:(.text+0xde): undefined reference to `g_type_check_instance_cast&apos;
et.o: In function `status_request_worker&apos;:
et.c:(.text+0x219): undefined reference to `notify_notification_new&apos;
et.c:(.text+0x229): undefined reference to `notify_notification_set_urgency&apos;
et.c:(.text+0x233): undefined reference to `notify_notification_show&apos;
et.c:(.text+0x255): undefined reference to `g_type_check_instance_cast&apos;
et.c:(.text+0x25d): undefined reference to `g_object_unref&apos;
et.o: In function `show_notification&apos;:
et.c:(.text+0xec): undefined reference to `g_object_unref&apos;
et.o: In function `main&apos;:
et.c:(.text.startup+0x11): undefined reference to `notify_init&apos;
et.c:(.text.startup+0x1a): undefined reference to `notify_is_initted&apos;
et.c:(.text.startup+0x27f): undefined reference to `notify_uninit&apos;
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target &apos;default&apos; failed
make: *** [default] Error 1
<font color="#8AE234"><b>egormanga@ACER-TOUCH</b></font>:<font color="#729FCF"><b>~/et</b></font>$ 
</pre>

**Comment by oxzi** [comment]
Thanks for trying to use `et` and reporting your problems. Could you please supply some information about your system, like

- what operating system and/or distribution are you using,
- do you have `libnotify` (and `libnotify-dev` or the like for Debian-based systems) installed and
- what does `pkg-config --cflags glib-2.0 gdk-pixbuf-2.0 --libs libnotify` return?

**Comment by oxzi** [comment]
I have to admit that the required dependencies are more written between the lines of the README instead of specified explicitly. You can check the provided [nix](https://github.com/geistesk/et/blob/master/default.nix) file, which lists the requirements. Furthermore I just fired up a Debian 9, installed `build-essential libnotify-dev` through `apt-get` and was able to build `et.`

Please answer my previous questions and I'd like to update the README with a more detailed install guide.

**Comment by egormanga** [comment]
Sorry for long answer.

* Ubuntu 18.04.2 LTS;
* All requirements are installed;
* Everything looks fine:
<pre><font color="#8AE234"><b>egormanga@ACER-TOUCH</b></font>:<font color="#729FCF"><b>~/et</b></font>$ pkg-config --cflags glib-2.0 gdk-pixbuf-2.0 --libs libnotify
-pthread -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lnotify -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0</pre>

**Comment by oxzi** [comment]
This was quite interesting. For debugging I created two containers based on Debian and Ubuntu with the same setup. However, the Ubuntu one failed to build this program. After some almost random changes I got it working.

@egormanga: Could you please retry building and verify the changes or reopen the issue otherwise?

**Comment by egormanga** [comment]
Yep, the last commit made it work. Thx.
