### ISSUE TITLE
[Feature request] Support changing message

### ISSUE THREAD

**Issue by enoryw** [geistesk/et#3]
Feature request: support editing a timer's message.

**Comment by oxzi** [comment]
Thanks for your request. I am currently a bit puzzled about how to implement this from a user experience point of view.

Since I wrote `et` for my workflow back then, which hasn't changed over the time, I'll just tell you how I use it:
1. I use `dmenu` to launch an `et` command like: `et 30:00 food`
2. Sometimes, another `et` instance will be launched, e.g., `et 120 tea`
3. As I am an inpatient person, I occasionally hit <kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>E</kbd> which is the keybinding for my build of dwm to launch `et-status`, querying the resulting time of all `et` instances.

By design, `et` is configured by its command line arguments and then pauses and waits for signals. There is no further user input, as it is not required by this "architecture". The `et-status.sh` script addresses all running `et` processes, not a specific one.

I could think of another helper script, which needs to know the specific `et` process, fetching its expected timer time, current run time and message, and recreate another new `et` process with the remaining time and a new message. Such a script, however, needs some level of user interaction if there is more than one `et` process running.

What do you think of this? How are you using `et` and how would you like to alter the message?

**Comment by enoryw** [comment]
I actually implemented my version as a [bash script](https://0x0.st/XJIb.txt) (I'm not much of a programmer so it's done in bash). It relies on the `sleep` command, which means it has the caveat of counting only machine time (doesn't count the time when the machine hibernates/sleeps(?)--I haven't tested whether `et` and similar timers work the same way but I assume they are real timers that go off based on actual system time. It uses bemenu (supports Wayland) but you can easily substitute with dmenu if it's not a straight up drop-in replacement.

I bound a hotkey to run `timer`, where it launches bemenu to prompt for message and then a time. The time supports `sleep` arguments like `2d 12m 1s` which is usually more succinct to type but I added support for specifying absolute time like `18:40` too. `timer --list` lists all the timers (including its remaining time) using dmenu and you can select a timer to set it to cancel/done (stops timer and marks it as done for the history), remove (stops timer and removes from history) or edit its message. The list also sorts it by upcoming timers. All of this including the timer (`sleep`'s PID) is tracked in a text file. It supports my status bar (`waybar` for Wayland) to keep a count of timers and hover to show all the timers.

I'm pretty satisfied with its UI but I'm not sure how hacky the implementation is (e.g. saving PID into a text file and killing that) but there's not been any bugs or unexpected behaviors. The biggest caveat is still the fact that `sleep` counts only the time the machine is awake, so if the machine is sleeping (pun intended) and wakes up, I believe it will return counting from when it started sleeping and all the timers get pushed back. That's what's keeping me interested in a dmenu-friendly timer that also supports the features described and implemented by my script. Since you're happy with `et` it's probably not worth your time implementing features you don't necessarily want but feel free to try it or make suggestions.

I also found this [similar timer tool](https://github.com/carrotfarmer/remindme) but I'm not sure if a simple timer app really needs a daemon running in the background.

**Comment by oxzi** [comment]
Thanks for coming back to this.

On 2024-08-20 14:50, enoryw ***@***.***> wrote:
> I haven't tested whether `et` and similar timers work the same way but
> I assume they are real timers that go off based on actual system time.

If you would have taken a look into et.c, which has only 200 lines
including whitespaces and comments, you would have seen it uses settimer
from the libc.

Please don't take this the wrong way. I am glad that you are happy with
your timer implementation and that it works for you, but it seems that
you did not even compile my little timer. So why bother creating this
issue if you're not interested in seeing it implemented.

> Since you're happy with `et` it's probably not worth your time
> implementing features you don't necessarily want but feel free to try
> it or make suggestions.

So far, I am not planing on changing this, as it literally "works for
me".

> I also found this [similar timer
> tool](https://github.com/carrotfarmer/remindme) but I'm not sure if a
> simple timer app really needs a daemon running in the background.

Funny, it kinds of reminds me of the good old at[0]. BTW, using at would
also allow implementing a timer application, allowing altering already
started timers.

[0]: https://man7.org/linux/man-pages/man1/at.1p.html
